# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# This is used with cargo-check-external-types to reduce the surface area of downstream crates from
# the public API. Ideally this can have a few exceptions as possible.
allowed_external_types = [
    "serde::ser::Serialize",
    "serde::de::Deserialize",
    "miette::protocol::Diagnostic",
    "weaver_forge::registry::ResolvedRegistry",
    "serde_json::value::Value",
    "weaver_resolved_schema::attribute::Attribute",
    "weaver_semconv::attribute::PrimitiveOrArrayTypeSpec",
    "weaver_common::Logger",
]
